Fix fzf-xxxxx

diff --git a/zsh/zfunc/fzf-ghq b/zsh/zfunc/fzf-ghq
--- a/zsh/zfunc/fzf-ghq
+++ b/zsh/zfunc/fzf-ghq
@@ -1,4 +1,12 @@
 fzf-ghq::print() {
+    if ! which ghq 1>/dev/null 2>&1; then
+        echo 'A "ghq" command is not found.'
+        return 1
+    fi
+    if ! which perl 1>/dev/null 2>&1; then
+        echo 'A "perl" command is not found.'
+        return 1
+    fi
     local s="$(ghq list --full-path | fzf -q "$1")"
     [[ -n $s ]] && print "cd $(echo $s | perl -lanE 'say $F[0]')"
 }
